// src/types/optionGroups.ts
export const GROUP_KEY = {
    HEATER_INSTALLATION: 'HEATER_INSTALLATION',
    HEATING_BASE: 'HEATING_BASE',
    HEATER_ADDONS_INTERNAL: 'HEATER_ADDONS_INTERNAL',
    HEATER_ADDONS_EXTERNAL: 'HEATER_ADDONS_EXTERNAL',
  
    COOLER_BASE: 'COOLER_BASE',
  
    MATERIALS_INTERNAL_BASE: 'MATERIALS_INTERNAL_BASE',
    MATERIALS_EXTERNAL_BASE: 'MATERIALS_EXTERNAL_BASE',
  
    INSULATION_BASE: 'INSULATION_BASE',
  
    SPASYSTEM_BASE: 'SPASYSTEM_BASE',
    LEDS_BASE: 'LEDS_BASE',
  
    LID_BASE: 'LID_BASE',
    COVER_BASE: 'COVER_BASE',
  
    FILTRATION_BASE: 'FILTRATION_BASE',
    FILTRATION_ADDONS: 'FILTRATION_ADDONS',
    SANDFILTER_BASE: 'SANDFILTER_BASE',
  
    STAIRS_BASE: 'STAIRS_BASE',
    CONTROLUNIT_BASE: 'CONTROLUNIT_BASE',
  
    EXTRAS_BASE: 'EXTRAS_BASE',
  } as const;
  
  export type GroupKey = typeof GROUP_KEY[keyof typeof GROUP_KEY];
  